In [ ]:
import pandas as pd
import numpy as np

print(pd.__version__)

2.3.1


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [ ]:
df.head

<bound method NDFrame.head of       engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Eu

In [ ]:
# rows, columns
df.shape

(9704, 11)

In [ ]:
# unique values
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [ ]:
# count of missing values for each column
df.isnull().sum()
# count of rows that have missing alies
#(df.isnull().sum() > 0).sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
# create new df only for origin = Asia
df_asia = df[df['origin'] == 'Asia']
df_asia

# find max fuel efficienty in this set
df_asia['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [ ]:
#Horsepower part 1 of 2
# backup dataset for practice and modifying
# pointing a new dataframe to the same array means changes are made to both df's
df_horse = df.copy()

# median horsepower = 149
df_horse['horsepower'].median()

# mode horsepower = 152
# 0 means pick the first of the values, not needed?
df_horse['horsepower'].mode()[0]

#replace null values with the mode
#inplace = True modifies this dataframe instead of making a replacement. Not necessary, use [0] and inplace is not needed
df_horse['horsepower'] = df_horse['horsepower'].fillna(df_horse['horsepower'].mode()[0])

#replace null values with 152 (manual calc, sub other numbers too for checking)
#df_horse['horsepower'] = df_horse['horsepower'].fillna(152)


In [ ]:
#Horsepower part 2 of 2
# check change
df_h_med = df_horse['horsepower'].median()
df_med = df['horsepower'].median()

# Evaluate change
if df_h_med > df_med:
    print('It went up')
elif df_h_med < df_med:
    print('It went down')
else: print ('SameSame')

It went up


In [ ]:
# Asia query
#Select all the cars from Asia
# done above in df_asia
df_asia = df[df['origin'] == 'Asia']

#Select only columns vehicle_weight and model_year
df_asia_subset = df_asia[['vehicle_weight', 'model_year']]

#Select the first 7 values
# pandas doesn't support [row, col] indexing like np
# use iloc to specify integer-location based indexing
df_asia_subset_seven = df_asia_subset.iloc[:7, :]
#print(df_asia_subset_seven)

#Get the underlying NumPy array. Let's call it X.
# x = np.array([df_asia_subset_seven]) this won't work, dataframe in brackets will create a 1-element object array
x = df_asia_subset_seven.to_numpy()

#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
# Capital T is transposing the array, @ is the matrix multiplication
# Not sure I understand this part
xtx = x.T @ x

#Invert XTX
# inverse is 1/ that number. Eg. 2 to the power of -1 means 1/2
# use pinv (pseudo inverse) instead of inv as this gives a result by finding best possible invert
xtx_inv = np.linalg.pinv(xtx)

#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# @ means matrix multiplication
# capital T means transpose
w = xtx_inv @ x.T @ y

#What's the sum of all the elements of the result?
w.sum()


np.float64(0.5187709081074039)

In [ ]:
#Array

In [ ]:
a = np.array([1,2,3,5,7,12])
a[2] = 10
np.arange(3, 10)
np.linspace(10,100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n=np.array([
    [1.1,1.2,1.3],
    [2.1,2.2,2.3],
    [3.1,3.2,3.3]
])
n

array([[1.1, 1.2, 1.3],
       [2.1, 2.2, 2.3],
       [3.1, 3.2, 3.3]])

In [ ]:
n[0,2]

np.float64(1.3)

In [ ]:
np.random.seed(5)
np.random.rand(5,2)
np.random.randn(5,2) #randn = normal dist
100 * np.random.randn(5, 2) # numbers between 0 and 100 vs standard 0-1
np.random.randint(low=0, high = 100, size = (5, 2)) # integers

array([[11, 67],
       [65, 55],
       [ 3, 91],
       [78, 27],
       [29, 33]])

In [ ]:
# Element Ops

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
aa = a + 1 # adds 1 to every number in array
b = (10 + (a * 2 )) ** 2  # ** means power of

In [ ]:
aa + b # adds numbers in arrays together, can do all kinds of functions here

array([101, 146, 199, 260, 329])